before:
  hooks:
    - go mod download
archives:
- files:
  - none*
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: x86_64
builds:
  - id: main
    main: ./main.go
    binary: airctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64